---
root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:vue/essential'
  - '@vue/standard'
  - '@vue/typescript'
  - 'prettier'
  - 'prettier/vue'
